name: Bug Report
description: File a bug report
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you start
        Please **make sure you are on the latest version of YTranscript.**

    - type: textarea
    id: what-happened
    attributes:
      label: Current behaviour
      description: |
        Tell us what happens instead of the expected behavior.
        Adding of screenshots really helps.
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us what **should** happen.
    validations:
      required: true

  - type: textbox
    id: link
    attributes:
      label: Youtube video link
      description: |
        Please provide link to youtube video which makes you trouble.
      placeholder: |
        https://www.youtube.com/watch?v=QgbLb6QCK88
    validations:
      required: false

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which Operating Systems are you using?
      description: You may select more than one.
      options:
        - label: Android
        - label: iPhone/iPad
        - label: Linux
        - label: macOS
        - label: Windows

  - type: input
    id: obsidian-version
    attributes:
      label: Obsidian Version
      description: Which Obsidian version are you using?
      placeholder: 0.15.9
    validations:
      required: true

  - type: checkboxes
    id: other-plugins-disabled
    attributes:
      label: Checks
      description: Please confirm
      options:
        - label: I have tried it with all other plugins disabled and the error still occurs
          required: false

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: |
        Not obligatory, but please suggest a fix or reason for the bug, if you have an idea.
